version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "dockerhub/username"
    DOCKERHUB_PASSWORD: "dockerhub/password"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/flask-secure-app:latest .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/flask-secure-app:latest
